#!/bin/bash
Notice="[RAR_TSDM.sh] "
path="${1%/*}/"
filename_ext="${1##*/}"
ConfigFile=/etc/aria2/aria2.conf

if [ "$2" = "F" ]; then 
    filename="${filename_ext}"
else
    filename="${filename_ext%.*}"
fi

# For RAR
header=[Inanity緋雪@TSDM]
PW=Inanity緋雪@僅分享於TSDM
CommentFile=/etc/aria2/comment.txt
targetFile=${header}${filename}.rar

# For Baidu
uploadDIR="/apps/bypy"
app_id=250528
LIST_API=https://pan.baidu.com/api/list
SHARE_API=https://pan.baidu.com/share/set
bdstoken=$(cat ${ConfigFile} | grep bdstoken | sed 's/.*=//')
logid=$(cat ${ConfigFile} | grep logid | sed 's/.*=//')
BD_Cookie=$(cat ${ConfigFile} | grep BD_COOKIE | sed "s/.*'\(.*\)'/\1/")
UserAgent="User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
sharePW=TSDM

# For LINE
LINE_API=https://notify-api.line.me/api/notify
LINE_TOKEN=$(cat ${ConfigFile} | grep LINE= | sed 's/.*=//' | sed 's/[^0-9A-Za-z]//')

# For TSDM
#FID=405 #吸血貓
#TYPE=3142 #4月
FID=8
TYPE=51
TSDM_Cookie=$(cat ${ConfigFile} | grep TSDM_COOKIE | sed "s/.*'\(.*\)'/\1/")
FORMHASH=eee3130b



echo "${Notice}Packaging \"$ {filename_ext}\" with RAR..."
rar a -hp"${PW}" -rr3 -idcdn -k -t -htb -c- -c -z"${CommentFile}" "${path}${targetFile}" "$1"
echo "${Notice}Uploading \"${targetFile}\" via pyby..."
bypy upload "${path}${targetFile}" -v
echo "${Notice}Upload finished."

# get file ID
echo "${Notice}Getting file ID..."
fileID=$(curl -sX GET "${LIST_API}?app_id=${app_id}&bdstoken=${bdstoken}&channel=chunlei&clienttype=0&desc=0&dir=${uploadDIR}&logid=${logid}==&num=100&order=name&page=1&showempty=0&web=1" --header 'Host: pan.baidu.com' --header "${UserAgent}" --header "${BD_Cookie}" | jq '.' | fgrep -B 13 "${targetFile}" | grep "fs_id" | sed 's/[^0-9]//g')

# create share link
echo "${Notice}Creating share link of ${fileID}..."
LINK=$(curl -sX POST "${SHARE_API}?bdstoken=${bdstoken}&channel=chunlei&web=1&app_id=${app_id}&logid=${logid}==&clienttype=0" --header 'Host: pan.baidu.com' --header "${UserAgent}" --header "${BD_Cookie}" --data-urlencode 'schannel=4' --data-urlencode 'channel_list=[]' --data-urlencode 'period=0' --data-urlencode "pwd=${sharePW}" --data-urlencode "fid_list=[${fileID}]" | jq '.link' | sed 's/.*"\(.*\)".*/\1/')
echo "${Notice}Your link is \"${LINK}\" with password \"${sharePW}\""

# push notify
echo "${Notice}Push notification to LINE..."
curl -sX POST ${LINE_API} --header 'Content-Type: application/x-www-form-urlencoded' --header "Authorization: Bearer ${LINE_TOKEN}" --data-urlencode \
"Message=        Task has been completed.
[Filename]： ${filename}
[Link]：         ${LINK}
[PW]：          ${sharePW}"; echo

# auto post to TSDM
echo "${Notice}Posting on TSDM..."
filesize=$(stat -c %s "${path}${targetFile}"|numfmt --to=iec)
curl -sX POST "https://www.tsdm39.net/forum.php?mod=post&action=newthread&fid=${FID}&topicsubmit=yes" --header "${TSDM_Cookie}" --form "formhash=${FORMHASH}" --form "typeid=${TYPE}" --form "subject=${filename}[${filesize}]" --form 'usesig="1"' --form 'allownoticeauthor="1"' --form 'addfeed="1"' --form 'wysiwyg="0"' --form "message=[align=center][b]This is a post generated by script wrote by Inanity緋雪, 
if you find any problem please contact me ASAP, thanks.[/align][/b]
LINK：[url]${LINK}[/url]   PW：${sharePW}

解壓碼：[b][color=Red][size=6]Inanity緋雪@僅分享於TSDM[/size][/color][/b]
備註：壓縮包皆含[color=DarkOrange]3%[/color]紀錄，若有壞檔請自行嘗試修復。" && echo

rm -rfv "${path}${targetFile}"
